### ISSUE TITLE
Enhance Custom constructor example

### ISSUE THREAD

**Issue by rsevero** [atreeon/morphy#1]
I am trying to understand the **Custom Constructors** [example](https://pub.dev/documentation/morphy/latest/#custom-constructors) but have the following doubts that, I believe, an enhanced example could easily solve:

1. Should the _a_Factory_ method be part of the abstract class that the user writes? Or is it a global method?
2. Should it be "static" or "factory"?
3. How am I expected to call this factory?
4. The property _privateConstructor_ seems to have been renamed to _hidePublicConstructor_

**Comment by atreeon** [comment]
HI @rsevero.  Firstly many apologies for the delay, I thought email notifications were turned on; I think they are now!

Secondly, you are right, there are a couple of errors with the example.  The main problem is that the morphy annotation is over the function instead of the class (entirely wrong!)

This is how it should read, does this help?  It should be simple.

> To allow custom constructors you can simply create a publicly accessible factory function that calls the constructor (ie just a method that calls the default constructor). 
> If you'd like to hide the automatic constructor set the `hidePublicConstructor` on the Morphy annotation to true.
> If you do hide the default constructor,  then in order for the custom factory function (A_FactoryFunction in the example below) to be able to call the hidden (or private) default constructor, your factory function should live in the same file you defined your class.
> 

 ```
    @Morphy(hidePublicConstructor: true)
    abstract class $A {
      String get val;
      DateTime get timestamp;
    }

    A A_FactoryFunction(String val) {
      return A._(val: val, timestamp: DateTime(2023, 11, 25));
    }

    var a = A_FactoryMethod("my value");

    expect(a.timestamp, DateTime(2023, 11, 25));
```

It is just a publicly accessible function that doesn't belong to the class that just calls the private constructor.

I would have liked to have made the constructor part of the class itself but I couldn't find an easy way to do it.  However the factory method pattern is a valid pattern.
